apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: phpenv
  name: phpenv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpenv
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: phpenv
    spec:
      containers:
        - args:
            - bash
            - -c
            - apt-get update && apt-get install -y libmariadb-dev && docker-php-ext-install mysqli && apache2-foreground
          env:
            - name: MYSQL_DBHOST
              value: mysqldb
            - name: MYSQL_DBNAME
              value: mydb
            - name: MYSQL_DBPASS
              value: root
            - name: MYSQL_DBPORT
              value: "3306"
            - name: MYSQL_DBUSER
              value: root
          image: php:8.0-apache
          name: phpenv
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: phpenv-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: phpenv-cm0
          name: phpenv-cm0
