apiVersion: v1
data:
  config.php: |
    <?php

    $servername = "mysqldb";

    $username = "root";

    $password = "root";

    $dbname = "mydb";

    $conn = new mysqli($servername, $username, $password, $dbname);

    if ($conn->connect_error) {

        die("Connection failed: " . $conn->connect_error);

    }

    ?>
  create.php: |
    <?php

    include "config.php";

      if (isset($_POST['submit'])) {

        $first_name = $_POST['firstname'];

        $last_name = $_POST['lastname'];

        $email = $_POST['email'];

        $password = $_POST['password'];

        $gender = $_POST['gender'];

        $sql = "INSERT INTO `users`(`firstname`, `lastname`, `email`, `password`, `gender`) VALUES ('$first_name','$last_name','$email','$password','$gender')";

        $result = $conn->query($sql);

        if ($result == TRUE) {

          echo "New record created successfully.";

        }else{

          echo "Error:". $sql . "<br>". $conn->error;

        }

        $conn->close();

      }

    ?>

    <!DOCTYPE html>

    <html>

    <body>

    <h2>Signup Form</h2>

    <form action="" method="POST">

      <fieldset>

        <legend>Personal information:</legend>

        First name:<br>

        <input type="text" name="firstname">

        <br>

        Last name:<br>

        <input type="text" name="lastname">

        <br>

        Email:<br>

        <input type="email" name="email">

        <br>

        Password:<br>

        <input type="password" name="password">

        <br>

        Gender:<br>

        <input type="radio" name="gender" value="Male">Male

        <input type="radio" name="gender" value="Female">Female

        <br><br>

        <input type="submit" name="submit" value="submit">

      </fieldset>

    </form>

    </body>

    </html>
  delete.php: |
    <?php

    include "config.php";

    if (isset($_GET['id'])) {

        $user_id = $_GET['id'];

        $sql = "DELETE FROM `users` WHERE `id`='$user_id'";

         $result = $conn->query($sql);

         if ($result == TRUE) {

            echo "Record deleted successfully.";

        }else{

            echo "Error:" . $sql . "<br>" . $conn->error;

        }

    }

    ?>
  index.php: |
    <?php
    	header('Content-Type: json_decode(json)');
    	header('Character-Encoding: utf-8');


        include "config.php";

        $sql = "SELECT * FROM users";

        $result = $conn->query($sql);
    ?>

    <!DOCTYPE html>
    	<html lang="pt-br">
    		<head>
    			<meta charset="utf-8">
    			<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
    			<title>PHPCRUD</title>
    			<link rel="stylesheet" href="css/estilo.css">
    		</head>
    		<body>
    			<div class="container">
    				<nav>
    					<ul class="menu">
    						<li><a href="view.php">View</a></li>
    						<li><a href="create.php">Create</a></li>
    						<li><a href="view.php">Update</a></li>
                            <li><a href="view.php">Delete</a></li>


    				</nav>
    			</div>
    		</body>
    	</html>

    	<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    	<script type="text/javascript" src="js/scripts.js"></script>
  update.php: |
    <?php

    include "config.php";

        if (isset($_POST['update'])) {

            $firstname = $_POST['firstname'];

            $user_id = $_POST['user_id'];

            $lastname = $_POST['lastname'];

            $email = $_POST['email'];

            $password = $_POST['password'];

            $gender = $_POST['gender'];

            $sql = "UPDATE `users` SET `firstname`='$firstname',`lastname`='$lastname',`email`='$email',`password`='$password',`gender`='$gender' WHERE `id`='$user_id'";

            $result = $conn->query($sql);

            if ($result == TRUE) {

                echo "Record updated successfully.";

            }else{

                echo "Error:" . $sql . "<br>" . $conn->error;

            }

        }

    if (isset($_GET['id'])) {

        $user_id = $_GET['id'];

        $sql = "SELECT * FROM `users` WHERE `id`='$user_id'";

        $result = $conn->query($sql);

        if ($result->num_rows > 0) {

            while ($row = $result->fetch_assoc()) {

                $first_name = $row['firstname'];

                $lastname = $row['lastname'];

                $email = $row['email'];

                $password  = $row['password'];

                $gender = $row['gender'];

                $id = $row['id'];

            }

        ?>

            <h2>User Update Form</h2>

            <form action="" method="post">

              <fieldset>

                <legend>Personal information:</legend>

                First name:<br>

                <input type="text" name="firstname" value="<?php echo $first_name; ?>">

                <input type="hidden" name="user_id" value="<?php echo $id; ?>">

                <br>

                Last name:<br>

                <input type="text" name="lastname" value="<?php echo $lastname; ?>">

                <br>

                Email:<br>

                <input type="email" name="email" value="<?php echo $email; ?>">

                <br>

                Password:<br>

                <input type="password" name="password" value="<?php echo $password; ?>">

                <br>

                Gender:<br>

                <input type="radio" name="gender" value="Male" <?php if($gender == 'Male'){ echo "checked";} ?> >Male

                <input type="radio" name="gender" value="Female" <?php if($gender == 'Female'){ echo "checked";} ?>>Female

                <br><br>

                <input type="submit" value="Update" name="update">

              </fieldset>

            </form>

            </body>

            </html>

        <?php

        } else{

            header('Location: view.php');

        }

    }

    ?>
  view.php: |+
    <?php

    include "config.php";

    $sql = "SELECT * FROM users";

    $result = $conn->query($sql);

    ?>

    <!DOCTYPE html>

    <html>

    <head>

        <title>View Page</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    </head>

    <body>

        <div class="container">

            <h2>users</h2>

    <table class="table">

        <thead>

            <tr>

            <th>ID</th>

            <th>First Name</th>

            <th>Last Name</th>

            <th>Email</th>

            <th>Gender</th>

            <th>Action</th>

        </tr>

        </thead>

        <tbody>

            <?php

                if (!empty($result) && $result->num_rows > 0) {

                    while ($row = $result->fetch_assoc()) {

            ?>

                        <tr>

                        <td><?php echo $row['id']; ?></td>

                        <td><?php echo $row['firstname']; ?></td>

                        <td><?php echo $row['lastname']; ?></td>

                        <td><?php echo $row['email']; ?></td>

                        <td><?php echo $row['gender']; ?></td>

                        <td><a class="btn btn-info" href="update.php?id=<?php echo $row['id']; ?>">Edit</a>&nbsp;<a class="btn btn-danger" href="delete.php?id=<?php echo $row['id']; ?>">Delete</a></td>

                        </tr>

            <?php       }

                }

            ?>

        </tbody>

    </table>

        </div>

    </body>

    </html>

kind: ConfigMap
metadata:
  labels:
    io.kompose.service: phpenv
  name: phpenv-cm0
